CC = g++

FLAGS = -W -Wall -Werror -O2

BIN = ../output/

BINFILE = LxcManager-server

OBJ = main.o \
    server.o \
    websockethandler.o

LIBS = -I/usr/local/include \
	-L/usr/local/lib \
	../websocketpp-api/libwebsocketpp.a \
	/usr/local/lib/libboost_system.a \
	/usr/local/lib/libboost_thread.a \
	/usr/local/lib/libboost_regex.a \
	/usr/local/lib/libboost_random.a \
	/usr/local/lib/libboost_date_time.a \
	-lpthread \
	-L/usr/lib/mysql \
	-lmysqlpp
